// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAa_NezhV1R9y_7rRpmMqxmVC9vN0nikNg',
    appId: '1:320626106468:web:4bef1d38620eef29f1ff71',
    messagingSenderId: '320626106468',
    projectId: 'fir-flutter-codelab-20535',
    authDomain: 'fir-flutter-codelab-20535.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-20535.firebasestorage.app',
    measurementId: 'G-GVJ1GMVLCE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9QiI1az768CC3lsetJd-HzhmHTDl3VhE',
    appId: '1:320626106468:android:76aedcccd0d074f4f1ff71',
    messagingSenderId: '320626106468',
    projectId: 'fir-flutter-codelab-20535',
    storageBucket: 'fir-flutter-codelab-20535.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDL0fqkPheLuSKa0fHEeVtwG4uy5dictwk',
    appId: '1:320626106468:ios:c035e96401ac0057f1ff71',
    messagingSenderId: '320626106468',
    projectId: 'fir-flutter-codelab-20535',
    storageBucket: 'fir-flutter-codelab-20535.firebasestorage.app',
    iosBundleId: 'com.example.firebaseDemo',
  );
}
